[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = { path = "../markdown" }

Inflector = "0.11"
include_dir = "0.7"
log = "0.4"
maud = "0.26"
serde = "1.0"
serde_yaml = "0.9"
tracing = "0.1.40"
